### ISSUE TITLE
Mixed tabs and spaces in docstrings

### ISSUE THREAD

**Issue by ashwinvis** [jleclanche/tan#10]
**Describe the bug** 

When multiline docstrings are used and formatted using `tan --use-tabs`, tabs get replaced by spaces.

**To Reproduce** Steps to reproduce the behavior:

1. Take this file 

```python
def a_func_with_docstrings(a):
	"""Tabs used for multiline docstrings

	Parameters
	----------
	a : int
		An integer

	Returns
	-------
	string

	"""
	print("A test function")
	return "Should use tab indents for code and docstrings."
```

2. Run _tan_ on it with these arguments '--use-tabs --check'
3. See error "Oh no! 💥 💔 💥
1 file would be reformatted."

**Expected behavior** A clear and concise description of what you expected to happen.

Should preserve tabs inside docstrings. Doing so leads to flake8 detect "E101 indentation contains mixed spaces and tabs"

**Environment (please complete the following information):**

- Version: 20.8.4
- OS and Python version: Linux/Python 3.8.5

**Does this bug also happen on master?** To answer this, you have two options:

Probably yes.

**Comment by sciyoshi** [comment]
This should be fixed in the latest release (21.14).
