### ISSUE TITLE
pull upstream

### ISSUE THREAD

**Issue by onlycs** [jleclanche/tan#11]
you are like 7000000 commits behind

**Comment by sciyoshi** [comment]
@jleclanche there was some significant refactoring upstream which actually made the patch simpler but might be a pain to preserve your commit history. If you want to see the patch against latest main it's here: https://github.com/sciyoshi/black/commit/faddb504b395c71a92e6a9ffadaafcc9413ecd88

**Comment by takeda** [comment]
@jleclanche any goal to apply @sciyoshi patch to continue the fork? There are valid reasons to use tabs over spaces, for example to reduce number of bytes in custom resource for cloud formation template.

**Comment by sciyoshi** [comment]
@jleclanche if you don't have the time and you're comfortable adding me as a contributor to this repo and on the PyPI package, I'd be happy to maintain this and keep it up-to-date.

**Comment by jleclanche** [comment]
@sciyoshi Just rebasing right now, will push an updated version in a moment.

**Comment by jleclanche** [comment]
@sciyoshi @TheAlphaReturns @takeda could you folks please try `tan==21.13`? I've rebased tan master against psf/black/main. It is indeed a lot simpler now that lines have a `mode` that carries over.

**Comment by sciyoshi** [comment]
It seems to be missing these changes (https://github.com/sciyoshi/black/commit/faddb504b395c71a92e6a9ffadaafcc9413ecd88#diff-98d222e4d1eed36d13bf2de2b3685fd3fbe65ff82450f30b77bfc11916cee76dR244-R246 and https://github.com/sciyoshi/black/commit/faddb504b395c71a92e6a9ffadaafcc9413ecd88#diff-431968a04535c5ee2570855fe3a3473527050ed0e6d5cb5a9544bcef254d0590R63-R70) which is needed for docstrings.

**Comment by jleclanche** [comment]
@sciyoshi You're right. I'm going to give you write access to the repo, you can push directly; let me know when you need me to do a release and I'll review. I just ask that you keep commit count and changes to an absolute minimum to keep things easy to rebase.

**Comment by sciyoshi** [comment]
Also I think https://github.com/jleclanche/tan/commit/e23c038167528bdacddd6779c6b4234e2634cfa3#diff-e82969837ee87e062540b0e41760ac6536b23c69dc9c8b1afc29783d10888849R390 should be `self.mode.use_tabs`

**Comment by sciyoshi** [comment]
```
[fellow] sciyoshi@sci ~/workspace/fellow/fellow (main) λ pip install tan==21.13
ERROR: Could not find a version that satisfies the requirement tan==21.13 (from versions: 21.13.linux-x86_64, 19.0.0, 19.0.1, 19.1.0, 19.1.1, 20.0.0, 20.0.2, 20.8, 20.8.1, 20.8.2, 20.8.3, 20.8.4)
ERROR: No matching distribution found for tan==21.13
[fellow] sciyoshi@sci ~/workspace/fellow/fellow (main) λ pip install tan==21.13.linux-x86_64
Collecting tan==21.13.linux-x86_64
  Downloading tan-21.13.linux-x86_64.tar.gz (294 kB)
     |████████████████████████████████| 294 kB 3.2 MB/s
ERROR: tan==21.13.linux-x86_64 from https://files.pythonhosted.org/packages/f0/d9/5169e3f00efc9c59125e1c7b86f0aef19595f0ca7a80aaa8be6ec590b615/tan-21.13.linux-x86_64.tar.gz#sha256=793039898ded622330fccd
71b9b21156b8188c6dc9d428a339d5daa6b8cdd61f does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```
Also the latest package seems to not install correctly.

**Comment by jleclanche** [comment]
> Also the latest package seems to not install correctly.

Urf, that's nasty. I did try using twine this time; I forgot how I did the release last time. Black could use a move to poetry…

**Comment by sciyoshi** [comment]
I pushed a commit with the changes here: https://github.com/jleclanche/tan/commit/997bb92ab8df9a3e6fd3e4e76a802f271b8a7e28.

**Comment by jleclanche** [comment]
@sciyoshi LGTM. Do you have any idea why the release I pushed didn't work? I used `setup.py build bdist; twine upload dist/*`. I don't have time to debug right now.

**Comment by takeda** [comment]
@jleclanche I just looked at the tarball uploaded and it installs binary files to `./usr/lib/python3.10/site-packages/`

What you probably meant is to produce the source tarball (`sdist` instead of `bdist`):

```sh
python setup.py sdist # source tarball
python setup.py bdist_wheel # wheel package
twine upload dist/<resulting files>
```
For bdist_wheel to work you need to have wheel package installed.

**Comment by jleclanche** [comment]
Okay, 21.14 should be good.

**Comment by takeda** [comment]
It appears to work. Some files changed formatting, but I believe Black also had some kind of change in formatting during that time.

Thanks!
