### ISSUE TITLE
Update tan to 22.1.0 against the stable black release

### ISSUE THREAD

**Issue by sciyoshi** [jleclanche/tan#12]
I've rebased the changes for tabs again onto the upstream stable release, version 22.1.0. The new branch is here: https://github.com/psf/black/compare/main...jleclanche:22.1

**Comment by sciyoshi** [comment]
@jleclanche I can push this to main if you're able to do a PyPI release for it.

**Comment by jleclanche** [comment]
Go for it, I'll push the release tomorrow.

**Comment by sciyoshi** [comment]
Done. Note that because of the removal of black-primer upstream (https://github.com/psf/black/pull/2809) the test suite should now be passing in CI!

**Comment by jleclanche** [comment]
Oh that's great. I'm not too bothered by that though anyway, as those problems are related to this being a fork with a different name (as I want people to be able to install it alongside black). So these wouldn't be in a PR.

**Comment by jleclanche** [comment]
Apologies for the long delay, this fell off my plate. tan 22.2.0 is released on pypi.
