### ISSUE TITLE
--use-tabs not respected at top of module

### ISSUE THREAD

**Issue by thebigmunch** [jleclanche/tan#2]
For example, defining a long ``__all__`` list at the top of the file will reformat it with spaces rather than tabs when using ``--use-tabs``. Options originating from black are respected.

**Comment by jleclanche** [comment]
I have no idea what's causing this.

**Comment by sciyoshi** [comment]
@jleclanche see my PR which addresses the issue, in particular commit https://github.com/jleclanche/tan/pull/5/commits/cfcb3928acd1b5390426594459b0fdaedd762cdd

**Comment by jleclanche** [comment]
@sciyoshi thanks very much! It works.  :) 

Uploaded 20.8.3
