### ISSUE TITLE
Question: Is this the recommended black --with-tabs project?

### ISSUE THREAD

**Issue by FredHappyface** [jleclanche/tan#27]
**Is your feature request related to a problem? Please describe.**

Hi a while ago I started working on a downstream project (to https://github.com/psf/black) to add tabs - something this project also does. I'm wondering if you would describe the project as a recommended means to achieve that same goal. I'd rather contribute in whatever way I can to this project rather than reinventing the wheel. Given the output of https://github.com/psf/black/issues/2798 and pretty much any other issue (https://github.com/psf/black/issues?q=is%3Aissue+tabs) it's clear that this isn't going to be accepted as a merge request upstream 

From my knowledge the following projects add tab support:
- https://github.com/jleclanche/tan
- https://github.com/MarcoGorelli/black-tabby-formatter
- https://github.com/FHPythonUtils/Blackt

**Describe the solution you'd like**

Would be brilliant if we had some sort of unofficial 'use this project for tab support'. Might it be worth adding a couple eager devs to the project to help maintain things? Or perhaps create an org?

**Describe alternatives you've considered**

Personally. Either continue using my fork (and fix bugs like https://github.com/FHPythonUtils/Blackt/issues/1) or use tan at risk (eg. the project becomes maintained)

**Additional context**

Thank you for your time :)

**Comment by takeda** [comment]
@FredHappyface this is kind of weird question to ask. I do use it and I hope it is being maintained. From the list that you gave I see:

- https://github.com/jleclanche/tan - this project
- https://github.com/MarcoGorelli/black-tabby-formatter - hacky solution, looks like it runs black then replaces spaces with tabs
- https://github.com/FHPythonUtils/Blackt - looks like it is your project

Unless @jleclanche no longer wants to maintain it, I think we should try to just concentrate on a single project and seems like this project is more popular.

**Comment by FredHappyface** [comment]
Don't entirely follow how it is a weird question. Yeah completely agree with you in regards to focusing on a single project. The reason I asked the question was precisely to avoid reinventing the wheel.

**Comment by jleclanche** [comment]
tan is written as a mergeable PR to black. But it looks like the black primary maintainer is as hostile as ever so I've stopped caring.
I use tan so I'll keep maintaining it whenever I get time or get pinged.

**Comment by FredHappyface** [comment]
Thanks for the clarification

I was aware of the um... Reluctance to merge this project

Thanks for your time and the awesome project

**Comment by takeda** [comment]
@FredHappyface by weird question I meant it is like asking if you prefer Ferrari or Lamborghini on Lamborghini forum. If it was my repo I would say that it's the recommended one to use, because I would be biased.

**Comment by danmacode** [comment]
If you just want black with tab support, I'd suggest migrating to ruff. 

- https://github.com/astral-sh/ruff

It will end up replacing black.
