### ISSUE TITLE
Bump to 22.8.0

### ISSUE THREAD

**Issue by sciyoshi** [jleclanche/tan#50]
Hi @jleclanche - I'm opening an issue to let you know that I'm planning on bumping tan to the latest upstream black release 22.8.0. There were only a few small conflicts this time. I've also removed the .github/dependabot.yml file to prevent the noise from the dependabot PRs (since this is enabled upstream, I don't think it serves any purpose here).

Separately, I think it might be useful to somehow automate or simplify the release process. One idea would be to have a git submodule of the upstream black version, two patch files (one for the fork, one for adding tab support), and a script to build/release. We could even add a scheduled GH action workflow to do this automatically.

Also - if you don't mind giving me access to the PyPI project (my username there is also sciyoshi), I can do the build/release process as well.

**Comment by sciyoshi** [comment]
The latest push to `master` should be good to go for a 22.8.0 release.

**Comment by jleclanche** [comment]
@sciyoshi thank you, i've added you to pypi.

**Comment by sciyoshi** [comment]
Thanks @jleclanche - 22.8.0 is released.
